# Generated by Django 4.2.1 on 2023-05-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_fastfood_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FastFood',
        ),
    ]
