# Generated by Django 4.2.1 on 2023-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_drinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='login',
            name='l_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
