# Generated by Django 4.2.1 on 2023-05-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_delete_drinks_rename_username_login_f_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
