# Generated by Django 4.2.1 on 2023-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=250, null=True)),
                ('drink_price', models.IntegerField(blank=True, max_length=200, null=True)),
                ('drink_ingredient', models.TextField(blank=True, null=True)),
                ('drink_image', models.ImageField(blank=True, null=True, upload_to='fast-food')),
                ('drink_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=255, null=True)),
                ('l_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('password', models.IntegerField(blank=True, max_length=150, null=True)),
                ('confirm_password', models.IntegerField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
