# Generated by Django 4.2.1 on 2023-05-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_drink_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
