# Generated by Django 4.2.1 on 2023-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
